theme:
  spacing: 8
  alpha: 0.9
  alphacss: e6

  bg: "191724"
  bg1: "21202e"
  bg2: "1f1d2e"
  fg: "e0def4"
  fg1: "908caa"
  fg2: "6e6a86"
  hllow: "21202e"
  hlmed: "403d52"
  hlhi: "524f67"
  primary: "eb6f92"
  secondary: "c4a7e7"
  border: "403d52"

colors:
  black: "191724"
  red: "eb6f92"
  green: "31748f"
  yellow: "f6c177"
  blue: "9ccfd8"
  magenta: "c4a7e7"
  cyan: "ebbcba"
  white: "e0def4"

border:
  size: 2
  radius: 2
