#!/usr/bin/env zsh

src() {
    [ -r "$1" ] && source "$1" > /dev/null 2> /dev/null
}

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE

alias ls='exa'
alias find='fd'
alias grep='rg'

alias ll='ls -al'
alias fzf='fzf-tmux -p'

# FZF
fzf_base_command="fd -L --color=always"
fzf_base_options="--ansi"

export FZF_DEFAULT_COMMAND="$fzf_base_command --type file"
export FZF_DEFAULT_OPTS=$fzf_base_options

export FZF_CTRL_T_COMMAND="$fzf_base_command --type file"
export FZF_CTRL_T_OPTS=$fzf_base_options

export FZF_ALT_C_COMMAND="$fzf_base_command --type directory"
export FZF_ALT_C_OPTS=$fzf_base_options

export FZF_TMUX=1
export FZF_TMUX_OPTS="-p"

src /usr/share/fzf/key-bindings.zsh
src /usr/share/fzf/completion.zsh

# editor
export EDITOR="hx"

# opam config
src /home/flo/.opam/opam-init/init.zsh

# npm config
src /usr/share/nvm/init-nvm.sh
export PNPM_HOME="$HOME/.local/share/pnpm"

export PATH="$PNPM_HOME:$HOME/.local/bin:$HOME/bin:$HOME/.cargo/bin:$HOME/go/bin:$PATH"

eval "$(oh-my-posh init zsh --config ~/.config/oh-my-posh/config.json)"

# direnv config
_direnv_hook() {
  trap -- '' SIGINT
  eval "$("/usr/bin/direnv" export zsh)"
  trap - SIGINT
}
typeset -ag precmd_functions
if (( ! ${precmd_functions[(I)_direnv_hook]} )); then
  precmd_functions=(_direnv_hook $precmd_functions)
fi
typeset -ag chpwd_functions
if (( ! ${chpwd_functions[(I)_direnv_hook]} )); then
  chpwd_functions=(_direnv_hook $chpwd_functions)
fi
