theme = "flo"

[editor]
scrolloff = 10
line-number = "relative"
cursorline = true
true-color = true
rulers = [80]
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "workspace-diagnostics", "register", "position",
   "position-percentage", "file-encoding"]

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
