[language-server.uiua-lsp]
command = "uiua"
args = ["lsp"]

[[language]]
name = "uiua"
scope = "source.uiua"
injection-regex = "uiua"
file-types = ["ua"]
roots = []
auto-format = true
comment-token = "#"
language-servers = [ "uiua-lsp" ]
indent = { tab-width = 2, unit = "  " }
shebangs = ["uiua"]

[[grammar]]
name = "uiua"
source.git = "https://github.com/shnarazk/tree-sitter-uiua"
source.rev = "c917a6cb115154a6b93b4812b50d7630565f4470"

[[language]]
name = "bash"
file-types = ["config", "sh", "bash", "zsh", ".bash_login", ".bash_logout",
  ".bash_profile", ".bashrc", ".profile", ".zshenv", ".zlogin", ".zlogout",
  ".zprofile", ".zshrc", "APKBUILD", "PKGBUILD", "eclass", "ebuild", "bazelrc",
  ".bash_aliases"]

[language-server.jdtls]
command = "jdtls"
args = [
  "-configuration", "/home/flo/.cache/jdtls/config",
  "-data", "/home/flo/.cache/jdtls/workspace",
]

[[language]]
name = "java"
scope = "source.java"
injection-regex = "java"
file-types = ["java"]
roots = ["pom.xml", "build.gradle"]
indent = { tab-width = 4, unit = "    " }
language-servers = ["jdtls"]

[[grammar]]
name = "java"
source.git = "https://github.com/tree-sitter/tree-sitter-java"
source.rev = "09d650def6cdf7f479f4b78f595e9ef5b58ce31e"
